"""phase2 core academic data: departments, programmes, course prereq/coreq/assessment, holidays, import jobs, and new columns on users/courses/registration_periods/academic_sessions

Revision ID: 42e5946fa0ab
Revises: 
Create Date: 2026-08-02 18:53:42.318640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42e5946fa0ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('faculty', sa.String(length=150), nullable=True),
    sa.Column('head_name', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('programmes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('program_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('academic_holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_session_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['academic_session_id'], ['academic_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_assessment_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('weight_percent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_corequisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('corequisite_course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['corequisite_course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'corequisite_course_id')
    )
    op.create_table('course_import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_prerequisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['prerequisite_course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'prerequisite_course_id')
    )
    op.create_table('student_import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_import_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_job_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_row', sa.Text(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['course_import_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_import_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_job_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_row', sa.Text(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['student_import_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('academic_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='draft', nullable=False))

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
        batch_op.add_column(sa.Column('max_capacity', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_courses_department_id_departments', 'departments', ['department_id'], ['id'])

    with op.batch_alter_table('registration_periods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('late_registration_ends_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('late_registration_fee', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('exam_starts_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('exam_ends_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('result_release_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('programme_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('account_status', sa.String(length=20), server_default='active', nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_users_programme_id_programmes', 'programmes', ['programme_id'], ['id'])
        batch_op.create_foreign_key('fk_users_department_id_departments', 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###

    # --- Data backfill: create Department rows from legacy free-text values,
    # and point existing users/courses at them via the new department_id FK.
    # programme_id is deliberately left NULL for all existing rows — there is
    # no reliable source data to backfill from (User.course today holds
    # arbitrary free text, not one of the three defined program types).
    import re
    from datetime import datetime
    from zoneinfo import ZoneInfo

    connection = op.get_bind()

    # departments.created_at is NOT NULL with a Python-side ORM default
    # (default=now_lagos) but no server_default, so a raw Core insert
    # (bypassing the ORM) must supply it explicitly. Same naive-Lagos-time
    # convention as models.now_lagos().
    backfill_now = datetime.now(ZoneInfo('Africa/Lagos')).replace(tzinfo=None)

    def slugify_code(name):
        base = re.sub(r'[^A-Z0-9]+', '', name.upper())[:15] or 'DEPT'
        return base

    users_table = sa.table(
        'users',
        sa.column('id', sa.Integer),
        sa.column('department', sa.String),
        sa.column('department_id', sa.Integer),
    )
    courses_table = sa.table(
        'courses',
        sa.column('id', sa.Integer),
        sa.column('department', sa.String),
        sa.column('department_id', sa.Integer),
    )
    departments_table = sa.table(
        'departments',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('code', sa.String),
        sa.column('status', sa.String),
        sa.column('created_at', sa.DateTime),
    )

    distinct_user_depts = {
        row[0] for row in connection.execute(
            sa.select(users_table.c.department).where(users_table.c.department.isnot(None))
        ).fetchall() if row[0] and row[0].strip()
    }
    distinct_course_depts = {
        row[0] for row in connection.execute(
            sa.select(courses_table.c.department).where(courses_table.c.department.isnot(None))
        ).fetchall() if row[0] and row[0].strip()
    }
    all_dept_names = sorted(distinct_user_depts | distinct_course_depts)

    existing_codes = set()
    name_to_id = {}
    for name in all_dept_names:
        base_code = slugify_code(name)
        code = base_code
        suffix = 1
        while code in existing_codes:
            suffix += 1
            code = f'{base_code}{suffix}'
        existing_codes.add(code)

        result = connection.execute(
            departments_table.insert().values(
                name=name, code=code, status='active', created_at=backfill_now
            )
        )
        # sa.table()/sa.column() are lightweight constructs with no primary-key
        # metadata, so inserted_primary_key can't be resolved from them; use
        # lastrowid directly (reliable here since departments.id is a SQLite
        # INTEGER PRIMARY KEY / rowid alias).
        name_to_id[name] = result.lastrowid

    users_matched = 0
    for name, dept_id in name_to_id.items():
        result = connection.execute(
            users_table.update().where(users_table.c.department == name).values(department_id=dept_id)
        )
        users_matched += result.rowcount

    courses_matched = 0
    for name, dept_id in name_to_id.items():
        result = connection.execute(
            courses_table.update().where(courses_table.c.department == name).values(department_id=dept_id)
        )
        courses_matched += result.rowcount

    total_users = connection.execute(sa.select(sa.func.count()).select_from(users_table)).scalar()
    total_courses = connection.execute(sa.select(sa.func.count()).select_from(courses_table)).scalar()
    print(f'[phase2 backfill] Created {len(name_to_id)} Department rows from distinct legacy strings.')
    print(f'[phase2 backfill] Backfilled department_id on {users_matched}/{total_users} users, '
          f'{courses_matched}/{total_courses} courses.')
    unmatched_users = total_users - users_matched
    if unmatched_users:
        print(f'[phase2 backfill] {unmatched_users} users had no department string set — '
              f'department_id left NULL, needs manual admin follow-up.')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_department_id_departments', type_='foreignkey')
        batch_op.drop_constraint('fk_users_programme_id_programmes', type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('account_status')
        batch_op.drop_column('programme_id')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('registration_periods', schema=None) as batch_op:
        batch_op.drop_column('result_release_at')
        batch_op.drop_column('exam_ends_at')
        batch_op.drop_column('exam_starts_at')
        batch_op.drop_column('late_registration_fee')
        batch_op.drop_column('late_registration_ends_at')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_courses_department_id_departments', type_='foreignkey')
        batch_op.drop_column('max_capacity')
        batch_op.drop_column('status')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('academic_sessions', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    op.drop_table('student_import_errors')
    op.drop_table('course_import_errors')
    op.drop_table('student_import_jobs')
    op.drop_table('course_prerequisites')
    op.drop_table('course_import_jobs')
    op.drop_table('course_corequisites')
    op.drop_table('course_assessment_components')
    op.drop_table('academic_holidays')
    op.drop_table('programmes')
    op.drop_table('departments')
    # ### end Alembic commands ###
