"""phase3 academic operations: registration_overrides table, last_login_at/onboarding_completed_at on users, is_locked/deadline_override on student_registrations, add_drop window on registration_periods

Revision ID: c95349c0e1ad
Revises: 42e5946fa0ab
Create Date: 2026-08-03 11:54:47.791756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c95349c0e1ad'
down_revision = '42e5946fa0ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_registration_id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['student_registration_id'], ['student_registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registration_periods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('add_drop_opens_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('add_drop_closes_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('student_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('deadline_override', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('onboarding_completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('onboarding_completed_at')
        batch_op.drop_column('last_login_at')

    with op.batch_alter_table('student_registrations', schema=None) as batch_op:
        batch_op.drop_column('deadline_override')
        batch_op.drop_column('is_locked')

    with op.batch_alter_table('registration_periods', schema=None) as batch_op:
        batch_op.drop_column('add_drop_closes_at')
        batch_op.drop_column('add_drop_opens_at')

    op.drop_table('registration_overrides')
    # ### end Alembic commands ###
